# when a branch is deleted, delete the repository associated with this branch
name: branch deleted

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#delete
on: delete

env:
  AWS_REGION: us-east-1
  # /!\ on master branch, to get the name of an other deleted branch,
  # you need to get { github.event.ref } instead of { github.ref_name }
  # https://stackoverflow.com/a/62293570
  ECR_REPOSITORY: multienv-vote-${{ github.event.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  delete:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Github variables
        run: |
          echo github.event.ref: ${{ github.event.ref }}
          echo github.ref_type: ${{ github.ref_type }}
          echo github.ref_name: ${{ github.ref_name }}
          echo github.sha: ${{ github.sha }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{secrets.OIDC_ROLE}}
          role-session-name: OIDCSession

      - name: Delete repository
        run: |
          aws ecr delete-repository \
            --repository-name ${{ env.ECR_REPOSITORY }} \
            --query 'repository.repositoryUri' \
            --output text \
            2>/dev/null
