# when a tag is pushed, create an ecr repository and build + push the image
name: tag

on:
  push:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-of-specific-tags-occurs
    tags: [ "v*.*.*" ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: lw-ps-ct-eks

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
    - name: Github variables
      run: |
        echo github.event.ref: ${{ github.event.ref }}
        echo github.ref_type: ${{ github.ref_type }}
        echo github.ref_name: ${{ github.ref_name }}
        echo github.sha: ${{ github.sha }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{secrets.OIDC_ROLE}}
        role-session-name: OIDCSession

    - name: Create ECR repo if missing
      uses: byu-oit/github-action-create-ecr-repo-if-missing@v1
      with:
        DOCKER_REPO_NAME: ${{ env.ECR_REPOSITORY }} # Your repo name goes here

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      # https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
      run: |
        cd vote
        docker image build \
          --build-arg NODE_ENV=production \
          --build-arg VERSION=${{ github.ref_name }} \
          --tag ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.ref_name }} \
          --tag ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest \
          .
        docker push --all-tags ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}
